apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    url: db:5432
    user: postgres
    secureJsonData:
      password: postgres
    jsonData:
      database: weatherdb
      sslmode: disable
      maxOpenConns: 100
      maxIdleConns: 100
      maxIdleConnsAuto: true
      connMaxLifetime: 14400
      postgresVersion: 1500
      timescaledb: false 